server:
  port: 4500
myCustomVar:
  devName: Claudio
  authCode: xyz458
---
environment: production
myCustomVar:
  devName: Vittorio
  authCode: xyz457
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 7070
---
environment: testing
myCustomVar:
  devName: NotProvided
  authCode: NoCode
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000